# Generated by Django 4.2.3 on 2023-07-05 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sulphite_safe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beveragesulphitestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beverage_sulphite_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sulphitestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sulphite_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beverages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beveragesulphitestatus',
            name='beverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beverage_sulphite_statuses', to='sulphite_safe_api.beverage'),
        ),
        migrations.AlterField(
            model_name='userbeveragesulphitestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
